use bzip2::read::BzDecoder;
use bzip2::write::BzEncoder;
use bzip2::Compression as Bzip2Compression;
use crc32fast::hash as crc32_hash;
use flate2::read::{DeflateDecoder, GzDecoder};
use flate2::write::GzEncoder;
use flate2::{Compression as GzipCompression, Decompress, FlushDecompress, Status};
use pyo3::prelude::*;
use pyo3::types::{PyBytes, PyDict, PyList};
use std::fs::{self, File};
use std::io::{self, Cursor, Read, Seek, SeekFrom, Write};
use std::path::{Path, PathBuf};
use std::time::{Duration, Instant};
use xz2::read::XzDecoder;
use xz2::write::XzEncoder;
use zstd::stream::read::Decoder as ZstdDecoder;
use zstd::stream::write::Encoder as ZstdEncoder;

include!("constants.rs");
include!("partial.rs");
include!("block_salvage.rs");
include!("../tar/compressed.rs");
include!("trim.rs");
include!("gzip.rs");
include!("zstd.rs");
include!("../tar/boundary.rs");
include!("types.rs");
include!("codec.rs");
include!("write.rs");
include!("gzip_helpers.rs");
include!("../tar/parse.rs");
include!("source.rs");
include!("result.rs");
include!("util.rs");
